### ISSUE TITLE
determine jsonld context to output from HTTP Accept header, not path

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/triannon#120]
- [x] OA dated context url in Accept  for jsonld
> Accept:  application/ld+json; profile="http://www.w3.org/ns/oa-context-20130208.json"

- [x] OA generic context url in Accept  for jsonld
> Accept:  application/ld+json; profile="http://www.w3.org/ns/oa.jsonld"

- [x] IIIF context url in Accept  for jsonld
>Accept:  application/ld+json; profile="http://iiif.io/api/presentation/2/context.json"

- [x] context specified for non jsonld (test that it is ignored)
>Accept:  application/x-turtle; profile="http://www.w3.org/ns/oa-context-20130208.json"

- [x] json profile specified incorrectly (3 context urls) - be nice and accept it
>Accept:  application/json; profile="http://iiif.io/api/presentation/2/context.json"

- [x] json format (3 mime types possible) + Link (3 context urls possible) + optional type
>Accept:  application/json
>Link: <http://www.w3.org/ns/oa.json>; rel="http://www.w3.org/ns/json-ld#context"; type="application/ld+json"

in all three flavors (per http://www.w3.org/TR/json-ld/#interpreting-json-as-json-ld)
type=blah is optional in Link header (refers to type of context doc)
the context url should be included in a plain json doc returned

- [x] json format with no Link (missing header, empty string in header, missing rel, missing first part ...)
- [x] json format with unrecognized Link Url
- [x] jsonld with Link Url (be nice and honor it)
- [x] non-json format with Link Url (Link ignored)

~~- [ ] and NOT part of the path or params (i.e. remove this code and tests)~~

For:
- [x] #show controller action
- [x] #create controller action

**Comment by ndushay** [comment]
See also #20 and #36 and #121

**Comment by azaroth42** [comment]
And (as discussed) accept in Content-Type for POST/PUT.
Should definitely not be part of path or params, as this is the same resource just a different representation.

**Comment by ndushay** [comment]
@azaroth42  says " You might get other URIs too I guess, and while F4 might deal with that we could reject them (at least for now) for Triannon"

**Comment by azaroth42** [comment]
@azaroth42 says put your finger on your nose!
