### ISSUE TITLE
determine jsonld context of POST/PUT from HTTP Content-Type header

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/triannon#121]
e.g.

    Content-Type: application/ld+json; profile="http://www.w3.org/ns/oa-context-20130208.json"

or

    Content-Type: application/ld+json; profile="http://www.w3.org/ns/oa.jsonld"

or

    Content-Type: application/ld+json; profile="http://iiif.io/api/presentation/2/context.json"

**Comment by azaroth42** [comment]
Being the inverse of #120 :+1:

**Comment by ndushay** [comment]
See also #36

**Comment by ndushay** [comment]
@azaroth42   If you look here:
```
Routes for Triannon::Engine:
          root GET    /                                          triannon/annotations#index
               GET    /annotations/:id(.:format)                 triannon/annotations#show
   annotations GET    /annotations(.:format)                     triannon/annotations#index
               POST   /annotations(.:format)                     triannon/annotations#create
new_annotation GET    /annotations/new(.:format)                 triannon/annotations#new
    annotation DELETE /annotations/:id(.:format)                 triannon/annotations#destroy
               GET    /annotations/:jsonld_context/:id(.:format) triannon/annotations#show
```

you will see that  requests can be 
> /annotations/my_id.json
/annotations/my_id.ttl

which are also "the same resource just a different representation".   So it's not clear to me that using params or path stuff is incorrect per rails.

**Comment by azaroth42** [comment]
The resource's URI is my_id, and the representations have the format. If my_id is requested, it should then do content negotiation and either return the format with a 200 response and the my_id.fmt in ContentLocation, or it should redirect to the my_id.fmt URI.

Hooray, content negotiation :(

**Comment by ndushay** [comment]
Per discussion with Rob, we have decided to expect the jsonld to have the context url inline, and we are NOT looking for it in the Content-Type header for jsonld (as above) or, for json format, in the Link header, e.g. 
>Link: <http://www.w3.org/ns/oa.json>; rel="http://www.w3.org/ns/json-ld#context"; type="application/ld+json"
