### ISSUE TITLE
config/triannon.yml might contain typo?

### ISSUE THREAD

**Issue by darrenleeweber** [sul-dlss/triannon#144]
`test: &test` might be a typo?  Please double check this line:
https://github.com/sul-dlss/triannon/blob/master/config/triannon.yml#L8

**Comment by cbeer** [comment]
Why do you say that? It looks like a perfectly valid use of the YAML anchor tags:

http://www.yaml.org/spec/1.2/spec.html#id2785586

(I'm not sure it's helping anyone, but it isn't broke.)
