### ISSUE TITLE
Authorization model

### ISSUE THREAD

**Issue by azaroth42** [sul-dlss/triannon#15]
Triannon must have a well defined model for authorization of different operations.  The model does not need to be fully implemented, but it must be clear how it could be implemented in the future.

- [ ] Model hooks in place
- [ ] Basic authorization model implemented
- [ ] Detailed authorization model implemented

(@ndushay @wmene to implement, plus @cbeer @azaroth42 to assist & document)

**Comment by ndushay** [comment]
@azaroth42  is this now superceded by #169 ?

**Comment by azaroth42** [comment]
Yep.
