### ISSUE TITLE
context caching - rest-client 1.8.0 issues

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/triannon#151]
See https://github.com/sul-dlss/triannon-service/issues/7.   When there is a fix, we should update the cache used for testing the gem.

**Comment by ndushay** [comment]
ruby-rdf/rdf#175 is merged. Wait for new gem release and then use faraday to cache. Modeled here:

ruby-rdf/rdf#176

**Comment by cbeer** [comment]
And now merged too. You should be able to use the Faraday adapter, and set the `FaradayAdapter.conn` to a Faraday::Connection with the cache middleware.

**Comment by darrenleeweber** [comment]
See also https://github.com/crohr/rest-client-components/pull/9

**Comment by ndushay** [comment]
when #151 is addressed, it should mean this can be closed.

**Comment by ndushay** [comment]
Gregg's fix https://github.com/crohr/rest-client-components/pull/9  was included in v1.4.0 of rest-client-components.

f339c022 addresses this.  Exploring memory cache before cutting new gem release

**Comment by ndushay** [comment]
Punting on in-memory cache #150 at this time.  Gem release 0.7.1 addresses this.
