### ISSUE TITLE
remove or improve /annotations/ route

### ISSUE THREAD

**Issue by azaroth42** [sul-dlss/triannon#154]
Currently a 7 second request to F4 takes more than 3 and a half minutes via Triannon. While this isn't a big deal while development is ongoing, it should be fixed or removed before deploying in case people try to use it.

**Comment by azaroth42** [comment]
Make as a search with no arguments to return the entire annotation set.  Dependent in the future on #162 when there's a lot of annos to deal with.

**Comment by ndushay** [comment]
Don't forget to deal with error responses from Solr

**Comment by ndushay** [comment]
![untitled](https://cloud.githubusercontent.com/assets/96775/7171499/233b3212-e38e-11e4-9a8b-dc7b2ff4ea6d.png)

**Comment by darrenleeweber** [comment]
Now that /annotations works off /search and therefore Solr, it should improve performance.  There should be no concerns about consistency and availability, as any POST will populate both F4 and Solr before it returns a successful response.  Therefore subsequent GET on /annotations from Solr will return the new annos.  This can be tested in the client specs in sul-dlss/triannon-client#4.

**Comment by ndushay** [comment]
- [x] merge this fix to master (#170)
- [ ] cut a new gem release with this fix
- [ ] deploy to dev
- [ ] deploy to stage
