### ISSUE TITLE
create oa-graph and use gem

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/triannon#165]
combine triannon::graph class with @darrenleeweber's sul-dlss/annotations2triannon/blob/master/lib/annotations2triannon/open_annotation.rb.  (look in branches of this code for latest greatest version.)  Also include:
 
- [x] remove_xxx_triples from rdf-fcrepo4 and rdf-ldp gems
- [x] jsonld context url namespaces
- [ ] annotations2triannon/open_annotation methods see #3

and other useful goodies.

- [x] use oa-graph gem in triannon @ndushay
- [ ] use oa-graph gem in annotations2triannon @darrenleeweber

**Comment by ndushay** [comment]
more accurately, combine with sul-dlss/annotations2triannon/blob/master/lib/annotations2triannon/open_annotation.rb

and look in branches of this code for latest greatest version.

**Comment by azaroth42** [comment]
Should be in separate repository for releases etc.

**Comment by ndushay** [comment]
See sul-dlss/oa-graph.   This is still a valid issue as triannon will need to be refactored when oa-graph is baked.

**Comment by ndushay** [comment]
I am closing this ticket;  the remaining work is represented in separate issues

* #3 - incorporate code from sul-dlss/annotations2triannon
* #7 - refactoring, esp array handling
* have sul-dlss/annotations2triannon use this gem (will get ticketed in that project)
