### ISSUE TITLE
Rob to verify Stakeholder Requirements

### ISSUE THREAD

**Issue by azaroth42** [sul-dlss/triannon#171]
* Mirador vs WebAuth
* Detail level of provenance description of user
  * Okay to store sunetid
  * Okay to publish sunetid?
  * Okay to publish name?
* Anticipated uses for Triannon Beta ... mirador w/o auth, plus auth'd SW?

**Comment by ndushay** [comment]
connected to #16

**Comment by azaroth42** [comment]
Lazy consensus that Mirador with authentication support is not a requirement, and we should design for authenticated SW demo.

**Comment by ndushay** [comment]
Also a question:  for Beta, are we talking about ONE ldap group with write permissions for SW, or multiple groups, or individuals?

**Comment by azaroth42** [comment]
Not individuals.

If you can do one group, is it hard to do more than one?

Also, I think the distinction between authenticated and not is interesting
-- e.g. anyone who has a sunetid might be able to create annotations/tags
on SW resources that are more highly regarded than the great unwashed.

So I think the killer demo for SW is:

* Allow anyone to annotate anything, but have the annotations ranked far
down the list
* Allow anyone who is authenticated to annotate anything, and promote them
* Allow one or more groups to annotate, such as catalogers and staff, and
always have them visible

Rob

**Comment by ndushay** [comment]
in the context of this ticket, my question was really "what is in scope for beta".   :smile_cat:

**Comment by azaroth42** [comment]
https://docs.google.com/document/d/13Iu3-hS-nSvQVd1M-Ph8RbjYhoMxETj42uRogTrJ4c4/edit#
