### ISSUE TITLE
Should triannon do LDAP lookup?

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/triannon#184]
There is an outstanding question (see comments) on whether:
1.  The client does the authentication and passes just the sunetid, then Triannon does the query to find out of the user is part of the workgroup.
2.  The client does the authentication and passes the sunetid AND all of the user's workgroups, then Triannon just does the comparison against the container's workgroup.
3.  The authorization should somehow happen outside of Triannon at the apache level

We need more information in order to answer the question.  The cleanest design is number 1. as it can be extended to other similar authorization patterns, however it may be difficult to acquire the permissions to have it work.  The second involves transferring potentially a large amount of information, some of which might be sensitive. The third creates a significant maintenance headache in the future.

@ndushay and @darrenleeweber are to work together with others in the department (especially @cbeer @wmene @eefahy @jkeck ) to figure this out.

**Comment by ndushay** [comment]
Willy sez:

"hmm, I've only done it in the context of webauth.  We configure the apache webauth module to only allow sunetids that belong to a specific set of LDAP/workfgroups.  Once they've authenticated and pass that check, the workgroup they belong to is set as an environment variable by the webauth module…

"but in your case, you need to do ad-hoc LDAP querying of workgroups, right?  I talked about this with Lynn, since we used to do that a lot in our previous department.  There are unix utilities/scripts where you can make those kinds of queries if you have the permission to do so....

"in this case, triannon, would have to shell out to that script/util to make the query….there's no way to do that type of querying through webauth, especially in your specific case where the user authenticates through searchworks, and triannon only receives some parameters on the back-end

"we haven't done this in DLSS yet"

**Comment by ndushay** [comment]
Willy sez

- [ ] we would need some kind of service principal that has the proper LDAP permissions to make those kind of queries

**Comment by ndushay** [comment]
@cbeer have we done anything like this in dlss yet?   @azaroth42

**Comment by ndushay** [comment]
@wmene says:

"probably want a wrapper around the ldapsearch client https://itservices.stanford.edu/service/directory/clientsoftware/commandline"

**Comment by ndushay** [comment]
@cbeer says 

"but if you’re already trusting SW to send you the right username, why not trust it to send the right workgroup?"

"if SW does it, it gets to use webauth, which we know how to do.  And you aren’t asking the powers that be for the power to look up random stuff in LDAP, just for specific users, so it’s probably an easier sell to the data owners."

**Comment by cbeer** [comment]
I don't know if we've done it in DLSS, and would strongly discourage it if there's a way to get e.g. searchworks to do the work for you, using plain old mod_webauthldap (that we already know how to use...).

**Comment by ndushay** [comment]
hmm.  Is this the right bits of work?

* get approp LDAP groups set up, and approp permissions to do LDAP group lookups given sunetid from webauth
* code approp LDAP group lookup in SW branch (along with "create an anno" - kinda like existing branch from @ndushay and @jchristo4 )
* code approp triannon write-it-to-the-correct-root-container based on SW POST info, trusting SW app to have done LDAP group lookup

* code approp webauth / LDAP group stuff for DMS annos (e.g. in sul-dlss/annotations2triannon)

and similarly for as yet unidentiied other triannon client apps --

**Comment by ndushay** [comment]
@wmene says:

"my guess is that you'd need the posixGroup attribute bundle for this service principal.  https://itservices.stanford.edu/service/directory/access/attributebundles"

**Comment by ndushay** [comment]
@wmene says:  "having (SW) do the lookup will only work if you know the set of all workgroups that you need to authenticate against"

**Comment by azaroth42** [comment]
Options discussed with @cbeer:
 * Lookup from Triannon -- we need to know first what permissions will be needed to do the (member in wg)? query, and if we can get them.  Secondly we need to know how to do that query.
 * Prefixed workgroups for triannon, that SW would send all of (e.g. triannon-library-dlss-staff).  However this would be a custom permission set, which we would need to get blessed, and know how to do.  It also means duplicating every useful set of users and keeping them up to date, rather than using existing sets.

If we were to do the second one, I'm not convinced that we should even use LDAP.  It would be much easier to maintain our own groups in Triannon than interact with LDAP.

**Comment by ndushay** [comment]
@LynnMcRae sez "to date we've only requested the level of privgroup look up that is released to webauth, so desired/alllowed (by stem) workgroup membership is passed into apps after webauth …  we are looking into the next level of independent privgroup query direct to ldap for Argo"

**Comment by ndushay** [comment]
@LynnMcRae sez  "why can't you just get the workgroup memberships passed in via webauth like apps typically do?"

@LynnMcRae sez  "establishing workgroups is a separate thing, via workgroup.stanford.edu … we have three established stems — sul (formerly sulair), sdr and dlss and more can be requested via HelpSU"

**Comment by ndushay** [comment]
@LynnMcRae sez "releasing membership to apps (via webaith or in general) is usually by stem, and only for stems that you (your group/app/etc) own and manage.  plus a public set of privgroups.  (workgroup names become privgroup entries in individual ldap entries, if that wasn't obvious)"

**Comment by azaroth42** [comment]
So we could create sul-triannon-* WGs and then maintain them, have SW and all other apps have to do the request and pass the information along, then Triannon needs to trust the app to do this accurately.  I see no value here compared to maintaining the groups outside of LDAP in Triannon, and the app just needs to pass the sunetid.

**Comment by ndushay** [comment]
i'm declaring the next step to be a meeting that will result in actual decisions on
# what exactly we're trying to support in Triannon (and why and with what deadlines)
# how exactly we will support those requirements.

**Comment by ndushay** [comment]
@LynnMcRae sez "there's a lot of semantics to be careful about as well … Parker has subscribers and institutions, non-sunetuid users and no real use for Stanford WGs beyond their role in defining "Stanford Community" …  Argo/DOR has roles and permissions which would be thought of as groups of people, but that leverages workgroups in order to assign independently managed institutionally or library managed populations to roles.
"whatever Triannon needs for internal authorization, it should not cut itself off from leveraging groups defined outside of triannon"

**Comment by ndushay** [comment]
@azaroth42 can this be closed now?

**Comment by azaroth42** [comment]
Yep!

**Comment by darrenleeweber** [comment]
I've reviewed this issue to catch up on the discussion.  There might be useful reference content that might be useful in the playbook?

**Comment by azaroth42** [comment]
:+1:
