### ISSUE TITLE
upgrade to fcrepo4 4.1.1

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/triannon#187]
in order to create Basic Containers (connected to #132) we need a more recent version of Fedora than Fedora 4.0.0-beta-04-SNAPSHOT,  which is what is currently in hydra-jetty deployed with triannon for development, and also used on fedora-dev and fedora-stage.

Instead of upgrading our fork of hydra-jetty, the intent is to use the latest released version of fcrepo4, which is 4.1.1.

This is connected to #73 , as using a released version implies dealing with the pair tree (and its slashes) in the triannon urls.

This is connected to #186 , as once we have this working with a released fedora, we can use the projecthydra/hydra-jetty and get rid of our fork.

This is connected to #132 as we need the fedora upgrade to create Basic Containers.

**Comment by ndushay** [comment]
@azaroth42 

Fedora 4.1.1 does something diff by default vis-a-vis container creation.   I want to check this:

über-root container:  Basic
each root container (e.g. “dms”, “lib-guides”, “sw”, etc.):   Basic
anno base container:  Basic  
/t and /b  containers:   Direct
specific  /t/xxx and /b/xxx  containers:   Basic


Is this correct?

**Comment by ndushay** [comment]
- [ ] ensure inline data is fedora 4.1.1 in specs
- [ ] cut a new release of gem.  note:  prob not backwards compatible.
- [ ] fedora dev uses released fedora (puppet scripts w devops involvement) (See SAR-2759)
- [ ] deploy new triannon to triannon dev
- [ ] fedora stage uses released fedora (puppet scripts w devops involvement) (See SAR-2759)
- [ ] deploy new triannon to triannon stage

**Comment by azaroth42** [comment]
Stamp of approval, sorry it took so long :)
