### ISSUE TITLE
media-type negotiation for retrieval

### ISSUE THREAD

**Issue by azaroth42** [sul-dlss/triannon#20]
When retrieving an annotation, a client will issue a GET request to Triannon.  This request may include an Accept header that asks for a particular serialization.  This request _should_ be supported for JSON, JSON-LD, Turtle and RDF/XML and may be supported for other serializations.  The default serialization is JSON-LD if not specified.
- [x] JSON-LD
- [x] Turtle
- [x] RDF/XML
- [x] JSON

For actions:
- [x] GET id / show
- [x] GET / index  (no id - a search)  (Covered by #117)
- [x] POST / create
- [x] GET new / new -> create
- [x] DELETE id / destroy (not relevant for delete)
- [x] PUT / update  (there will be no PATCH)  (Covered by #13)
- [x] GET id/edit -> edit -> update  (there will be no edit)

**Comment by ndushay** [comment]
implemented for POST (#create) with commit  7ce674a.  Still needs tests

**Comment by ndushay** [comment]
addressed with #124 and remaining parts to be addressed by #117 and #13
