### ISSUE TITLE
http://localhost:3000/ encounters redirect to /annotations and throws 500 response

### ISSUE THREAD

**Issue by darrenleeweber** [sul-dlss/triannon#202]
For the latest master branch, the server at http://localhost:3000/ redirects to /annotations and that fails; the console log shows:
```console
Started GET "/" for 127.0.0.1 at 2015-06-18 13:53:43 -0700


Started GET "/annotations" for 127.0.0.1 at 2015-06-18 13:53:43 -0700

ArgumentError (wrong number of arguments (2 for 1)):
  actionpack (4.2.0) lib/action_dispatch/http/request.rb:338:in `parse_query'
  rack (1.6.3) lib/rack/request.rb:191:in `GET'
  actionpack (4.2.0) lib/action_dispatch/http/request.rb:300:in `GET'
  actionpack (4.2.0) lib/action_dispatch/http/parameters.rb:14:in `parameters'
  actionpack (4.2.0) lib/action_dispatch/http/filter_parameters.rb:37:in `filtered_parameters'
  actionpack (4.2.0) lib/action_controller/metal/instrumentation.rb:22:in `process_action'
  actionpack (4.2.0) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
  activerecord (4.2.0) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
```

**Comment by darrenleeweber** [comment]
When running `rake` on a fresh git clone (in the master branch), there are 49 failures.

**Comment by cbeer** [comment]
I suspect Rack 1.6.3 was buggy -- they've since released Rack 1.6.4 and I'm not seeing any test failures.

**Comment by darrenleeweber** [comment]
Ok, updated to rack 1.6.4 and everything passes using the VCR data in the repo.  However, after `rm -rf spec/internal; rm -rf spec/fixtures/vcr_cassettes/*` and then running `rake`, there are a lot of test failures (181).  The test suite should be more robust and this might be a problem with using VCR data on a regular basis because code changes may be passing with stale data.

**Comment by darrenleeweber** [comment]
BTW, the Gemfile.lock is in gitignore, so there's a chance we may have a different bundle of gems.

**Comment by darrenleeweber** [comment]
Update:  specs are passing after:
```console
bundle update
rm -rf spec/internal; rm -rf spec/fixtures/vcr_cassettes/*
# in another console session
rake  triannon:jetty_reset # which starts the jetty services
# in the spec console session
rake
```

Also, the http://localhost:3000/ is redirecting to /annotations OK.  So I have to conclude that the bundle update and re-initializing the jetty container services has resolved this issue.  The remaining issues are:
  - whether or not the default rake task should detect missing VCR data and then initialize the jetty container services and
  - whether .gitignore should include Gemfile.lock or not

**Comment by azaroth42** [comment]
If we re-encounter, we'll re-report it. Too many changes in recent time to know a priori :)
