### ISSUE TITLE
auth timeouts are configuration parameters

### ISSUE THREAD

**Issue by darrenleeweber** [sul-dlss/triannon#203]
The authentication parameters for client/access token timeouts should be configuration params.  The current values of 60/3600 are probably fine for most use cases (i.e. reasonable defaults).

**Comment by darrenleeweber** [comment]
This should be fixed in 58f052d, which will be reviewed at some point in a PR for the `feature/auth-ish` branch.

**Comment by darrenleeweber** [comment]
@ndushay & @azaroth42 - thanks for the suggestion & confirmation to configure these values.

**Comment by azaroth42** [comment]
:+1: :beers:
