### ISSUE TITLE
Add webauth workgroups to the authentication workflow

### ISSUE THREAD

**Issue by darrenleeweber** [sul-dlss/triannon#210]
@azaroth42 and @ndushay - let's define the specs for the WebAuth-WorkGroups mapping to annotation containers and how that should work in the authentication work flow, considering both the SearchWorks and the DMS ETL use cases.  In these specs, we need to be clear about how different HTTP methods are to function (e.g. GET may not require any authentication).

**Comment by darrenleeweber** [comment]
Assigning this to @ndushay as this will be ready when we integrate the current auth work into master.

**Comment by azaroth42** [comment]
Done :)
