### ISSUE TITLE
Triannon code should work and specs should pass with slashes (pair tree) in the URLs

### ISSUE THREAD

**Issue by wmene** [sul-dlss/triannon#73]
1. Test that Triannon works with the default Fedora4 installed by DevOps.
2. Test that Triannon will continue to work with (new) default Fedora4 URI generation algorithm (ab/cd/abcd-1234...) e.g. in 4.1.1

Original: Fedora4 by default generates URLs with extra slashes in the path.  Initial development was against a patched version of fedora which created URLs without the slashes.  We need to have triannon work with URLs with extra slashes

**Comment by azaroth42** [comment]
Do we have a test for this to prove it's working as expected?

**Comment by ndushay** [comment]
I don't know that it *is* working yet.  So no, we do not have a test yet.

**Comment by azaroth42** [comment]
@wmene If you recall this issue, was it that F4 might generate a path with // in it? Or just that it adds / to the end of URLs as needed for containers?  The first would be a problem, (need a solution with test), the second seems to be working as expected (and can just close the issue)

**Comment by ndushay** [comment]
Begin forwarded message:

From: Willy Mene <wmene@stanford.edu>
Subject: Slashes in fedora4 URLs
Date: October 27, 2014 at 11:41:13 AM PDT
Cc: Naomi Dushay <ndushay@stanford.edu>
To: Rob Sanderson <azaroth@stanford.edu>

Hey Rob,

When fedora4 creates new resources, the URL's to reach them have extra subpaths added as a prefix.  For example, if you create a new resource at 
http://localhost:8983/fedora/rest

The URL to that new resource is:
http://localhost:8983/fedora/rest/b8/86/ba/b7/b886bab7-45b4-4739-aaec-153b2e8e98aa

When we started triannon development, we built our own fedora4 war files where the intermediate sub-paths were removed.  The URL to our example resource then becomes:
http://localhost:8983/fedora/rest/b886bab7-45b4-4739-aaec-153b2e8e98aa

Our question is, should we care about the intermediate subpaths?  We initially brought up the need to have a different build of fedora4 as an issue with the hydra-jetty project https://github.com/projecthydra/hydra-jetty/issues/29 .  Now that I think about it, I tend to agree with Chris.

We're maintaining our own fork of hydra-jetty with a slashless fedora4, but longer term, it could become a maintenance burden.  We would like to use the fedora4 that everyone else uses.

Willy

**Comment by ndushay** [comment]
Begin forwarded message:

Date: October 27, 2014 at 4:14:29 PM PDT
From: Rob Sanderson <azaroth@stanford.edu>
To: Chris Beer <cabeer@stanford.edu>
Cc: Willy Mene <wmene@stanford.edu>, Naomi Dushay <ndushay@stanford.edu>
Subject: Re: Slashes in fedora4 URLs


In theory, I agree, but people still often look at the URIs that get minted.  It's certainly not crucial that either Fedora or Triannon do it.

To make a decision, just let F4 make its own URIs until someone complains.  At which point having a Slug generator function that can be configured would be valuable.

Rob

On 10/27/14, 4:09 PM, Chris Beer wrote:
If it cares that much. I’d suggest it shouldn’t.

On Oct 27, 2014, at 4:08 PM, Rob Sanderson <azaroth@stanford.edu> wrote:


So should Triannon then mint its own UUIDs and use them as Slugs?

R


On 10/27/14, 12:07 PM, Chris Beer wrote:
The additional paths are there to get the best performance out of the underlying storage layer (until they fix their bug.. some day). If you don’t care about your identifiers, the repository gives you one that works best for it.


On Oct 27, 2014, at 11:52 AM, Rob Sanderson <azaroth@stanford.edu> wrote:


Hrm.

I agree with Chris to a certain extent, in that if we care about the URLs then they can be provided with a Slug... but creating a bunch of redundant path segments seems undesirable unless there's a real reason to have them.

Chris? Isn't this just pulling in the pair-tree like structure from the first part of the UUID? Is there a good reason to do that, when it seems that just the UUID is sufficiently unique?

Rob

**Comment by ndushay** [comment]
The only reason I can think of that slashes in the uuids would matter is for parsing out your base-url, parent containers and slugs.   If we have know baseurl and parent (root) containers (and we do - in a config .yml file), and we have known slugs (e.g.  "b" and "t" at the lowest level), then this concern could become moot.

@cbeer says "my big suggestion is don’t fork fedora; there’s configuration that you should be able to use without #73.. and then, fix #73, because it’s the right thing to do."

we *ought* to be able to run fedora with env variables set to avoid slashes, if we want to:

https://github.com/fcrepo4/fcrepo4/blob/master/fcrepo-webapp/src/main/resources/spring/minter.xml#L9-10

**Comment by ndushay** [comment]
I am closing this in favor of #186 (and #187) -- if we are using Fedora 4.1.1 vanilla, then we are using the Fedora ids which have the pair tree prefixes.  With the changes for Fedora 4.1.1 in #188, we know that triannon works with the pair tree prefixes used by Fedora.
