### ISSUE TITLE
context caching improvement

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/triannon#96]
See https://github.com/ruby-rdf/json-ld/issues/13:

per Gregg Kellogg:
"(commit  85eb3d7)  takes advantage of changes to RDF::Util::File.open_file. If you require restclient/components you can get RestClient to use Rack::Cache, which gives a broad way to deal with client-side caching. See the doc for RDF::Util::File.open_file for more details."

current app behavior is to just substitute an inline context when we encounter certain URLs.

**Comment by ndushay** [comment]
this has been at least partially addressed (see ruby-rdf/json-ld#13)

**Comment by ndushay** [comment]
important to address before we go to production.

**Comment by ndushay** [comment]
Date: March 11, 2015 at 2:53:20 PM PDT
From: Darren Weber <dlweber@stanford.edu>
To: Naomi Dushay <ndushay@stanford.edu>
Cc: Rob Sanderson <azaroth@stanford.edu>, Willy Mene <wmene@stanford.edu>
Subject: Re: caching context for jsonld

I looked into it and read Greg's proposed solution at
https://github.com/ruby-rdf/rdf/blob/develop/lib/rdf/util/file.rb#L33

The solution implemented and working OK looks like this (in an init):

```
# Using rest-client with options to enable
# a client HTTP cache
require 'rest-client'
require 'restclient/components'
require 'rack/cache'
# RestClient.enable Rack::CommonLogger, STDOUT
RestClient.enable Rack::Cache
# Cache common json-ld contexts
contexts = [
 'http://iiif.io/api/image/1/context.json',
 'http://iiif.io/api/image/2/context.json',
 'http://iiif.io/api/presentation/1/context.json',
 'http://iiif.io/api/presentation/2/context.json',
 'http://www.shared-canvas.org/ns/context.json'
]
contexts.each {|c| RestClient.get c }
```
It might be good to "prime" additional contexts, but the RestClient/rack-cache setup caches everything anyhow.  So, this relies on the rack-cache to handle all the details of HTTP cache protocols.  The cost of this is added deps on rack, rack-cache, restclient/components, but it was easy to implement ;-)

-- Darren

**Comment by darrenleeweber** [comment]
A revised implementation is in https://github.com/sul-dlss/annotations2triannon/blob/master/lib/requires.rb#L11-L35, i.e.

```
# Using rest-client with options to enable
# a client HTTP cache
require 'rest-client'
if ENV['RACK_CACHE_ENABLED'].to_s.upcase == 'TRUE'
    require 'dalli'
    require 'restclient/components'
    require 'rack/cache'
    RestClient.enable Rack::CommonLogger, STDOUT
    # Enable the HTTP cache to store meta and entity data according
    # to the env config values or the defaults given here. See
    # http://rtomayko.github.io/rack-cache/configuration for available options.
    metastore = ENV['RACK_CACHE_METASTORE'] || 'file:/tmp/cache/meta'
    entitystore = ENV['RACK_CACHE_ENTITYSTORE'] || 'file:/tmp/cache/body'
    verbose = ENV['RACK_CACHE_VERBOSE'].to_s.upcase == 'TRUE' || false
    RestClient.enable Rack::Cache,
        :metastore => metastore, :entitystore => entitystore, :verbose => verbose
    # Prime the HTTP cache with some common json-ld contexts used for
    # IIIF and open annotations.
    contexts = [
        'http://iiif.io/api/image/1/context.json',
        'http://iiif.io/api/image/2/context.json',
        'http://iiif.io/api/presentation/1/context.json',
        'http://iiif.io/api/presentation/2/context.json',
        'http://www.shared-canvas.org/ns/context.json'
    ]
    contexts.each {|c| RestClient.get c }
end
```

**Comment by ndushay** [comment]
Need this for searching #127

**Comment by ndushay** [comment]
addessed by #148 and in version 0.6.0
