### ISSUE TITLE
get list of all annos for a particular target

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/triannon#98]
For Hydra::Works and compatibility with Lynette's work, there should be the option of an ore:Aggregation with proxy nodes supplying the order.  This ties in to #102 and #101, I think.

At which point we would need the context for ORE in JSON-LD. One exists, but it makes the proxy construction harder than it needs to be.  See issue here:  https://github.com/projecthydra-labs/hydra-works/issues/35

Issue probably needs to be split out into multiple.

**Comment by ndushay** [comment]
#108, #109 covered this.  Wahoo!  Also implemented code in https://github.com/sul-dlss/searchworks/tree/ld4l to use this.

**Comment by aeschylus** [comment]
Double Plus Good!
